### ISSUE TITLE
Improve Usability of Code

### ISSUE THREAD

**Issue by thijsmie** [niksudan/gms2-destructible-scenery#3]
Hi! I just wanted to make a few remarks on what I think are good ideas, feel free to ignore:

Try to abstract your code to scrips. This makes it easy to run multiple instances of your code. Return an array with your surface and grid so you can pass it into other scripts easily:

    /// destructable_terrain_create(w, h, cellsize)
    ....
    return [surface, grid, cellsize]

    /// destructable_terrain_draw(x, y, grid)`
    /// destructable_terrain_destroy(relative_x, relative_y, radius, grid)`

A very important thing is that surfaces are _volatile_. This means it is not guaranteed that they aren't randomly destroyed! An easy fix would be to automagically recreate your surface from the grid in the draw script:

    if (!surface_exists(surface)) {
        surface = surface_create(ds_grid_width(grid) * cellsize);
        argument2[@ 0] = surface; //Write with no copy to the original array to remember the new surface
        for(var i = 0; i < ds_grid_width(grid); i++)
             for(var j = 0; j < ds_grid_height(grid); j++)
                 draw_rectangle(i*cellsize, j*cellsize, (i+1)*cellsize, (j+1)*cellsize, false);
    }

**Comment by niksudan** [comment]
Thanks for your feedback! I made this in under an hour as a little test project, so I missed out a lot of things. Abstraction is something I'd definitely add in for readability and reusability.

Also good point about volatile surfaces! Brings back memories to previous projects of mine crashing due to surface problems.
